"use client";
import { useState } from "react";
import Link from "next/link";

export default function ReportsPage() {
  const [generating, setGenerating] = useState(false);
  const [report, setReport] = useState<null | { title: string; summary: string; sections: { title: string; content: string }[] }>(null);
  const [firNumber, setFirNumber] = useState("CR-045/2024");

  const handleGenerate = async () => {
    setGenerating(true);
    await new Promise(r => setTimeout(r, 2000));
    setReport({
      title: `Investigation Report — ${firNumber}`,
      summary: "AI-generated comprehensive investigation report for Karnataka State Police. Confidence: 84%",
      sections: [
        { title: "1. Executive Summary", content: "Armed robbery at Vijay Petroleum, Koramangala on 10-Mar-2024 at 21:45 hrs. Three masked suspects decamped with ₹1,42,000. Primary suspect Ravi Kumar S (KSP-CR-2024-0001) is a known repeat offender with 12 prior FIRs, currently absconding. CCTV evidence available. Similar MO to 2 prior robberies in South Bangalore." },
        { title: "2. Incident Overview", content: "Date: 10-Mar-2024, 21:45 hrs | Location: Vijay Petroleum, Koramangala 5th Block, Bangalore 560095 | Category: Robbery u/s 392/397/34 IPC / 309 BNS | Loss: ₹1,42,000 cash | Weapons used: Sharp-edged weapons (blades)" },
        { title: "3. Suspect Analysis", content: "PRIMARY: Ravi Kumar S (KSP-CR-2024-0001) — Age 34, repeat offender, 12 FIRs, leader of Bengaluru South Gang, absconding since 2022. High probability match via facial recognition from CCTV partial footage (72%).\nCO-ACCUSED 1 & 2: Unidentified. Working on CCTV enhancement." },
        { title: "4. Evidence Summary", content: "• CCTV footage (60 sec) from petrol station Camera 3 — partial plate visible\n• Witness statement from petrol pump attendant (corroborated)\n• Blood sample from scene — sent to CFSL Bangalore for DNA analysis\n• Motorcycle partial registration: KA-01-?? recovered from adjacent shop CCTV" },
        { title: "5. Recommended Actions", content: "1. Issue Lookout Circular for Ravi Kumar S nationwide\n2. Apply KCOCA provisions given gang activity pattern\n3. Coordinate with Shivajinagar PS for ground surveillance\n4. Obtain CDR data from Jio/Airtel for towers within 1km radius on 10-Mar-2024\n5. Enhance CCTV footage for plate identification (RFSL)\n6. Cross-reference DNA with NCRB database" },
        { title: "6. Legal Sections", content: "Primary: IPC Section 392 (Robbery — up to 10 years)\nAggravated: IPC Section 397 (Robbery with deadly weapon — min 7 years)\nCommon intention: IPC Section 34\nBNS Equivalent: Sections 309, 310\nRecommendation: Apply KCOCA 2000 given organized gang pattern" },
      ]
    });
    setGenerating(false);
  };

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold" style={{ fontFamily: "'Rajdhani', sans-serif" }}>
            AI Investigation Reports
          </h1>
          <p className="text-sm mt-1" style={{ color: "var(--text-muted)" }}>
            Generate comprehensive reports from case data using POLICEGPT AI
          </p>
        </div>
      </div>

      {/* Generator */}
      <div className="chart-container">
        <h3 className="text-sm font-semibold mb-4" style={{ color: "var(--text-primary)" }}>
          🤖 Generate AI Report
        </h3>
        <div className="flex gap-3 flex-wrap">
          <div>
            <label className="text-xs block mb-1" style={{ color: "var(--text-muted)" }}>FIR Number</label>
            <input value={firNumber} onChange={e => setFirNumber(e.target.value)}
              className="pg-input" style={{ width: "200px" }} placeholder="e.g. CR-045/2024" />
          </div>
          <div className="flex items-end">
            <button onClick={handleGenerate} disabled={generating} className="btn-primary text-sm px-6 py-2.5">
              {generating ? (
                <><div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" /> Generating...</>
              ) : (
                <><span>📄</span> Generate Report</>
              )}
            </button>
          </div>
        </div>
      </div>

      {/* Report Output */}
      {report && (
        <div className="chart-container space-y-4">
          <div className="flex items-start justify-between">
            <div>
              <h2 className="text-lg font-bold" style={{ color: "var(--accent-blue-bright)" }}>{report.title}</h2>
              <p className="text-xs mt-1" style={{ color: "var(--text-muted)" }}>
                Generated by POLICEGPT v1.0 • {new Date().toLocaleString("en-IN")} • {report.summary}
              </p>
            </div>
            <div className="flex gap-2">
              <button className="btn-ghost text-xs px-3 py-1.5">📥 Export PDF</button>
              <button className="btn-ghost text-xs px-3 py-1.5">📧 Share</button>
            </div>
          </div>

          <div className="h-px" style={{ background: "var(--border-primary)" }} />

          {report.sections.map((s, i) => (
            <div key={i} className="py-3" style={{ borderBottom: i < report.sections.length - 1 ? "1px solid rgba(30,64,120,0.2)" : "none" }}>
              <h3 className="text-sm font-semibold mb-2" style={{ color: "var(--accent-blue)" }}>{s.title}</h3>
              <p className="text-sm whitespace-pre-line" style={{ color: "var(--text-secondary)", lineHeight: "1.8" }}>{s.content}</p>
            </div>
          ))}

          <div className="p-3 rounded-lg text-xs" style={{ background: "rgba(59,130,246,0.08)", border: "1px solid rgba(59,130,246,0.2)", color: "var(--text-muted)" }}>
            ⚠️ This report is AI-generated for investigation assistance. Verify all facts from official CCTNS records before using in court proceedings.
          </div>
        </div>
      )}
    </div>
  );
}
